version: '3.1'

volumes:
  gems:

services:
  db:
    image: postgres:9.6
    ports:
      - 5432:5432
    env_file:
      - secret-envs/dev-db.env
    volumes:
      - /postgres:/var/lib/postgresql/data

  redis:
    image: redis:3.2-alpine
    ports:
      - 6379:6379
    volumes:
      - /redis:/var/lib/redis/data

  server_app:
    build: dockerfiles/be.Dockerfile
    command: >
      /bin/bash -c "
      bundle exec rake db:create &&
      bundle exec rake db:migrate &&
      exec bundle exec rails server"
    ports:
      - 3000:3000
    env_file:
      - secret-envs/dev-server.env
    volumes:
      - .:/home/www/airplanner
      - gems:/bundler
    depends_on:
      - db
      - redis
    restart: on-failure

  sidekiq:
    build: dockerfiles/be.Dockerfile
    command: bundle exec sidekiq -C config/sidekiq.yml
    ports:
      - 3001:3001
    env_file:
      - secret-envs/dev-server.env
    depends_on:
      - db
      - redis
    restart: on-failure
