version: '3.1'

volumes:
  redis:
  postgres:
  bundle_path:

services:
  db:
    image: postgres:9.6
    ports:
      - 5428:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airplanner_development
    volumes:
      - postgres:/var/lib/postgresql/data

  in_memory_store:
    image: redis:3.2-alpine
    ports:
      - 6378:6379
    volumes:
      - redis:/var/lib/redis/data

  server_app: &server_app
    build: .
    command: >
      /bin/bash -c "
      rm -f $APP_HOME/tmp/pids/server.pid &&
      rm -f $APP_HOME/tmp/pids/sidekiq.pid &&
      bundle exec rake db:create &&
      bundle exec rake db:migrate &&
      exec bundle exec rails server --binding 0.0.0.0"
    volumes:
      - .:/home/www/airplanner
      - bundle_path:/bundle
    restart: on-failure
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: airplanner_development
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      REDIS_DB: "redis://in_memory_store:6379"
      SECRET_KEY_BASE: STUB
      DEVISE_SECRET_KEY: STUB
    depends_on:
      - db
      - in_memory_store
    ports:
      - 3000:3000

  server_worker_app:
    <<: *server_app
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - db
      - server_app
      - in_memory_store
    ports:
      - 3001:3001
