version: '3.1'

volumes:
  assets:
  gems:

services:
  db:
    image: postgres:9.6
    env_file:
      - secret-envs/prod-db.env
    volumes:
      - /postgres:/var/lib/postgresql/data

  redis:
    image: redis:3.2-alpine
    volumes:
      - /redis:/var/lib/redis/data

  server_app:
    image: 840573575565.dkr.ecr.us-east-1.amazonaws.com/airplanner/server_app:staging
    build: dockerfiles/be.Dockerfile
    command: >
      /bin/bash -c "
      bundle exec rake db:create &&
      bundle exec rake db:migrate &&
      exec bundle exec puma -C config/puma.rb"
    ports:
      - 3000:3000
    volumes:
      - assets:/home/www/airplanner/public/assets
      - .:/home/www/airplanner
      - gems:/bundler
    restart: on-failure
    env_file:
      - secret-envs/prod-server.env
    depends_on:
      - db
      - redis

  sidekiq:
    build: dockerfiles/be.Dockerfile
    command: bundle exec sidekiq -C config/sidekiq.yml
    env_file:
      - secret-envs/prod-server.env
    depends_on:
      - db
      - redis
    restart: on-failure

  nginx:
    image: 840573575565.dkr.ecr.us-east-1.amazonaws.com/airplanner/nginx:staging
    build: ./dockerfiles/nginx.Dockerfile
    context: ./datum/nginx
    command: >
      /bin/bash -c "
      /usr/bin/prepare-config.sh &&
      exec nginx -g daemon off"
    volumes:
      - assets:/home/www/airplanner/public/assets
    env_file:
      - secret-envs/prod-nginx.env
    ports:
      - 80:8080
    depends_on:
      - server_app
