default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['POSTGRES_PORT'] %>
  database: <%= ENV['POSTGRES_DATABASE_NAME'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['POSTGRES_DATABASE_NAME'] || 'airplanner_development' %>

test:
  <<: *default
  database: airplanner_test

staging:
  <<: *default
  database: <%= ENV['POSTGRES_DATABASE_NAME'] || 'airplanner_staging' %>

production:
  <<: *default
